# Server
server.port=8080
spring.application.name=api-gateway

# JWT secret — must match auth-service exactly
jwt.secret=${JWT_SECRET}

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Swagger UI Aggregation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth-service
springdoc.swagger-ui.urls[0].name=Auth Service

springdoc.swagger-ui.urls[1].url=/v3/api-docs/product-service
springdoc.swagger-ui.urls[1].name=Product Service

springdoc.swagger-ui.urls[2].url=/v3/api-docs/warehouse-service
springdoc.swagger-ui.urls[2].name=Warehouse Service

springdoc.swagger-ui.urls[3].url=/v3/api-docs/purchase-service
springdoc.swagger-ui.urls[3].name=Purchase Service

springdoc.swagger-ui.urls[4].url=/v3/api-docs/supplier-service
springdoc.swagger-ui.urls[4].name=Supplier Service

springdoc.swagger-ui.urls[5].url=/v3/api-docs/movement-service
springdoc.swagger-ui.urls[5].name=Movement Service

springdoc.swagger-ui.urls[6].url=/v3/api-docs/alert-service
springdoc.swagger-ui.urls[6].name=Alert Service

springdoc.swagger-ui.urls[7].url=/v3/api-docs/report-service
springdoc.swagger-ui.urls[7].name=Report Service

# Logging — INFO in prod
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.stockhub=INFO

# CORS — update allowedOrigins to your actual frontend URL in prod
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=${FRONTEND_URL}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.default-filters=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

spring.main.web-application-type=reactive