#server
server.port=8087
spring.application.name=alert-service

#database
spring.datasource.url=jdbc:mysql://localhost:3306/stockhub_alert
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=utkarshraj309@gmail.com
spring.mail.password=rjugkbzlhwpvugbb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Admin email to receive critical alerts
app.alert.admin-email=shishirkr.sbv@gmail.com
app.alert.from-email=utkarshraj309@gmail.com

# Feign timeout settings  //5 sec wait for connection and response
spring.cloud.openfeign.client.config.default.connect-timeout=5000  
spring.cloud.openfeign.client.config.default.read-timeout=5000

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
# API docs path
springdoc.api-docs.path=/v3/api-docs
# Show all endpoints including actuator
springdoc.show-actuator=false
# Sort endpoints alphabetically
springdoc.swagger-ui.operations-sorter=alpha

#RabbitMq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Show debug logs
logging.level.com.stockhub=DEBUG