#server
server.port=8087
spring.application.name=alert-service

#database
spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/stockhub_alert
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:8761/eureka/
eureka.instance.prefer-ip-address=true

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Admin email to receive critical alerts
app.alert.admin-email=${ADMIN_EMAIL}
app.alert.from-email=${FROM_EMAIL}

# Feign timeout settings
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false
springdoc.swagger-ui.operations-sorter=alpha

#RabbitMq
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.configs.default.sliding-window-size=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.WarehouseClientgetAllWarehouses.register-health-indicator=true
resilience4j.circuitbreaker.instances.WarehouseClientgetStockByWarehouse.register-health-indicator=true
resilience4j.circuitbreaker.instances.ProductClientgetProductById.register-health-indicator=true
resilience4j.circuitbreaker.instances.AuthClientgetUsersByRole.register-health-indicator=true

# Logging — INFO in prod, not DEBUG
logging.level.com.stockhub=INFO