#server
server.port=8761
spring.application.name=eureka-server

#eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# In Docker, hostname = the container service name defined in docker-compose
eureka.instance.hostname=${EUREKA_HOST}
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:8761/eureka

#dashboard
eureka.server.enable-self-preservation=false